<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>HydroTrain</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Management" />
    <Reference Include="PdfSharp">
      <HintPath>..\..\Documents\Apps\2.0\LBRK531Z.4YB\MPJ372AK.OY1\hydr..tion_1499838d4134a423_0004.0000_31db5fe8f04c904a\PdfSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Speech" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <Reference Include="System.DirectoryServices" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>